server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tipovacka_db
    username: root
    password: SimpleAndTrivial
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
logging:
  level:
    com.example.tipovacka: DEBUG
    org.springframework.web: DEBUG
    org.springdoc: DEBUG
    org.springframework.security: DEBUG
  file:
    name: logs/tipovacka.log
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs