server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tipovacka_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: SimpleAndTrivial
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
logging:
  level:
    com.example.tipovacka: DEBUG
    org.springframework.web: DEBUG
    org.springdoc: DEBUG
    org.springframework.security: DEBUG
  file:
    name: logs/tipovacka.log
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    encoding: UTF-8
  api-docs:
    enabled: true
    path: /v3/api-docs
    charset: UTF-8