server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tipovacka_db
    username: root
    password: SimpleAndTrivial
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true