name: API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: SimpleAndTrivial
          MYSQL_DATABASE: tipovacka_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package
    
    - name: Build and Run Spring Boot
      run: |
        mvn spring-boot:run &
        sleep 30 # Počkáme na nastartování aplikace
        
    - name: Install Newman
      run: npm install -g newman
      
    - name: Run Postman Tests
      run: |
        newman run ./postman/tipovacka.postman_collection.json -e ./postman/local.postman_environment.json
        if [ $? -ne 0 ]; then
          echo "Postman tests failed"
          exit 1
        fi 